from __future__ import annotations

CODE_AUTHORING_SCHEMA_COMPILE_ERROR = "authoring_schema_compile_error"
CODE_SCHEMA_VALIDATION_ERROR = "schema_validation_error"
CODE_EMPTY_PREDICATES = "empty_predicates"

CODE_REGISTRY_RULE_ERROR = "registry_rule_error"
CODE_RULE_SPEC_ERROR = "rule_spec_error"
CODE_RULE_COMPILE_ERROR = "rule_compile_error"
CODE_AUTHORING_RULE_COMPILE_ERROR = "authoring_rule_compile_error"

CODE_DERIVATION_PREVIEW_ERROR = "derivation_preview_error"
CODE_AUTHORING_DERIVATION_COMPILE_ERROR = "authoring_derivation_compile_error"

CODE_PREVIEW_TRUNCATED = "preview_truncated"
CODE_SOUFFLE_BINARY_MISSING = "souffle_binary_missing"
CODE_TEMPORAL_CURRENT_NO_PRED_REFS = "temporal_current_no_pred_refs"
CODE_TEMPORAL_CURRENT_NO_TEMPORAL_SCHEMA_PREDICATES = (
    "temporal_current_no_temporal_schema_predicates"
)
CODE_TEMPORAL_CURRENT_NO_TEMPORAL_WHERE_PREDICATES = (
    "temporal_current_no_temporal_where_predicates"
)

AUTHORING_ERROR_CODES_V1 = (
    CODE_AUTHORING_SCHEMA_COMPILE_ERROR,
    CODE_SCHEMA_VALIDATION_ERROR,
    CODE_REGISTRY_RULE_ERROR,
    CODE_RULE_SPEC_ERROR,
    CODE_RULE_COMPILE_ERROR,
    CODE_AUTHORING_RULE_COMPILE_ERROR,
    CODE_DERIVATION_PREVIEW_ERROR,
    CODE_AUTHORING_DERIVATION_COMPILE_ERROR,
)

AUTHORING_WARNING_CODES_V1 = (
    CODE_EMPTY_PREDICATES,
    CODE_PREVIEW_TRUNCATED,
    CODE_SOUFFLE_BINARY_MISSING,
    CODE_TEMPORAL_CURRENT_NO_PRED_REFS,
    CODE_TEMPORAL_CURRENT_NO_TEMPORAL_SCHEMA_PREDICATES,
    CODE_TEMPORAL_CURRENT_NO_TEMPORAL_WHERE_PREDICATES,
)

AUTHORING_DIAGNOSTIC_CODES_V1 = tuple(
    dict.fromkeys((*AUTHORING_ERROR_CODES_V1, *AUTHORING_WARNING_CODES_V1))
)

AUTHORING_DIAGNOSTIC_CODES_V1_SET = frozenset(AUTHORING_DIAGNOSTIC_CODES_V1)

